"""Reinformer: Device Placement Analysis

Data sources:
  baseline_results.json  — generated by run_baselines.py  (CPU-only, GPU-only, Random)
  rl_results.json        — produced by RL/SCOTCH scripts   (SCOTCH, RL-algorithms, …)

Both files use the same entry format:
  {
    "placement":        {"op_id": "device_id", ...},
    "simulation_result": <output of simulation_result_to_dict()>,
    "training_curve":   [{"step": int, "reward": float}, ...]   <- RL only
  }

Run order:
  1. python run_baselines.py       -> baseline_results.json
  2. RL placement results after running the simulator    is dumped here. It follows the same output structure as step 1. rl_results.json
  3. python plot_analysis.py
"""
from __future__ import annotations
import json
from pathlib import Path
from typing import Dict, List, Optional

import matplotlib
matplotlib.use("Agg")
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT   = SCRIPT_DIR.parent

GRAPH_PATH          = REPO_ROOT / "graph_bert_optimized.json"
BASELINE_RESULTS    = SCRIPT_DIR / "baseline_results.json"
RL_RESULTS_PATH     = SCRIPT_DIR / "rl_results_template.json"

OUT_DIR = SCRIPT_DIR / "figures"
OUT_DIR.mkdir(parents=True, exist_ok=True)

BASE_COLORS    = {"CPU-only": "#4C72B0", "GPU-only": "#DD8452", "Random": "#C44E52"}
METHOD_PALETTE = ["#8172B2", "#55A868", "#937860", "#DA8BC3", "#8C8C8C"]
plt.rcParams.update({"font.size": 11, "figure.dpi": 150})



def cross_device_bytes(ops: List[Dict], placement: Dict[str, str]) -> float:
    by_id = {op["id"]: op for op in ops}
    total = 0.0
    for child in ops:
        for pid in child.get("dependencies", []):
            parent = by_id.get(pid)
            if parent and placement.get(parent["id"]) != placement.get(child["id"]):
                total += sum(t.get("size_bytes", 0) for t in parent.get("output_tensors", []))
    return total


def _save(fig: plt.Figure, name: str) -> None:
    fig.savefig(OUT_DIR / name, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved {name}")


def _color(name: str, idx: int) -> str:
    return BASE_COLORS.get(name, METHOD_PALETTE[idx % len(METHOD_PALETTE)])


def _parse_entry(name: str, d: Dict, ops: List[Dict]) -> Optional[Dict]:
    """Extract runtime, comm_bytes, placement from a baseline or method entry."""
    sim = d.get("simulation_result", {})
    pl  = d.get("placement", {})
    rt  = sim.get("total_runtime") if sim.get("status") == "OK" else d.get("total_runtime")
    if rt is None:
        return None
    return {
        "name":           name,
        "runtime":        rt,
        "comm_bytes":     cross_device_bytes(ops, pl) if pl else 0.0,
        "placement":      pl,
        "training_curve": d.get("training_curve", []), #this is for rl training curve
    }



def plot_runtime_comparison(baselines: Dict, methods: List[Dict]) -> None:
    """Here, we plot Latency bar chart; speedup vs CPU-only annotated in green text."""
    fig, ax = plt.subplots(figsize=(10, 5))
    cpu_rt = baselines.get("CPU-only", {}).get("runtime")
    pos, ticks, labels = 0, [], []

    for name, d in baselines.items():
        rt = d["runtime"] * 1000
        bar = ax.bar(pos, rt, 0.6, color=_color(name, 0), alpha=0.9, zorder=3)
        ax.bar_label(bar, fmt="%.2f ms", padding=4, fontsize=9)
        if cpu_rt and name != "CPU-only":
            ax.text(pos, rt * 1.10, f"{cpu_rt/d['runtime']:.2f}×",
                    ha="center", fontsize=9, color="#2a7a2a", fontweight="bold")
        ticks.append(pos); labels.append(name); pos += 1

    for i, m in enumerate(methods):
        rt = m["runtime"] * 1000
        bar = ax.bar(pos, rt, 0.6, color=_color(m["name"], i), alpha=0.9, zorder=3)
        ax.bar_label(bar, fmt="%.2f ms", padding=4, fontsize=9)
        if cpu_rt:
            ax.text(pos, rt * 1.10, f"{cpu_rt/m['runtime']:.2f}×",
                    ha="center", fontsize=9, color="#2a7a2a", fontweight="bold")
        ticks.append(pos); labels.append(m["name"]); pos += 1

    ax.set_xticks(ticks); ax.set_xticklabels(labels, rotation=10, ha="right")
    ax.set_ylabel("Simulated Latency (ms)")
    ax.set_title("BERT Inference Latency by Placement Strategy  (green text= speedup vs CPU-only)")
    ax.grid(axis="y", alpha=0.3, zorder=0); ax.set_ylim(bottom=0)
    fig.tight_layout()
    _save(fig, "fig1_runtime_comparison.png")


def plot_training_curve(baselines: Dict, methods: List[Dict]) -> None:
    """RL convergence curves; baselines as dashed reference lines."""
    fig, ax = plt.subplots(figsize=(10, 4.5))
    has_curve = any(m.get("training_curve") for m in methods)

    for i, m in enumerate(methods):
        if m.get("training_curve"):
            curve = m["training_curve"]
            ax.plot([pt["step"] for pt in curve], [-pt["reward"] * 1000 for pt in curve],
                    linewidth=2, label=m["name"], color=_color(m["name"], i))

    for name, d in baselines.items():
        ax.axhline(d["runtime"] * 1000, linestyle="--", linewidth=1.5, alpha=0.7,
                   color=_color(name, 0), label=f"{name} ({d['runtime']*1000:.2f} ms)")

    if not has_curve:
        ax.text(0.5, 0.5, "Add training_curve to rl_results_template.json to populate",
                ha="center", va="center", fontsize=12, color="#888", transform=ax.transAxes)

    ax.set_xlabel("Training Steps"); ax.set_ylabel("Latency (ms)  [= −reward]")
    ax.set_title("RL Convergence  (baselines = dashed)")
    ax.legend(fontsize=9, loc="upper right"); ax.grid(alpha=0.3)
    fig.tight_layout()
    _save(fig, "fig2_training_curve.png")


def plot_per_op_scatter(ops: List[Dict]) -> None:
    """Log-log scatter: per-op CPU vs GPU runtime. This motivates mixed placement."""
    cpu_rts, gpu_rts = [], []
    for op in ops:
        rod = op.get("runtime_on_device", {})
        if "cpu:0" in rod and "gpu:0" in rod:
            cpu_rts.append(rod["cpu:0"])
            gpu_rts.append(rod["gpu:0"])
    if not cpu_rts:
        print("Skip: no ops with both CPU+GPU runtimes")
        return

    cpu = np.array(cpu_rts) * 1e6
    gpu = np.array(gpu_rts) * 1e6
    colors = [BASE_COLORS["CPU-only"] if c < g else BASE_COLORS["GPU-only"] for c, g in zip(cpu, gpu)]

    fig, ax = plt.subplots(figsize=(6, 6))
    ax.scatter(cpu, gpu, c=colors, alpha=0.6, s=40, zorder=3)
    lo, hi = min(cpu.min(), gpu.min()) * 0.7, max(cpu.max(), gpu.max()) * 1.4
    ax.plot([lo, hi], [lo, hi], "k--", alpha=0.4, linewidth=1.5)
    ax.set_xscale("log"); ax.set_yscale("log")
    ax.set_xlim(lo, hi); ax.set_ylim(lo, hi)
    ax.set_xlabel("CPU Runtime (μs)"); ax.set_ylabel("GPU Runtime (μs)")

    n_cpu = int(sum(c < g for c, g in zip(cpu, gpu)))
    n_gpu = len(cpu) - n_cpu
    ax.set_title(f"Per-Op Runtime: CPU vs GPU  ({len(cpu)} ops)\n"
                 f"Blue = CPU faster ({n_cpu})  |  Orange = GPU faster ({n_gpu})")
    ax.legend(handles=[
        mpatches.Patch(color=BASE_COLORS["CPU-only"], label=f"CPU faster ({n_cpu} ops)"),
        mpatches.Patch(color=BASE_COLORS["GPU-only"], label=f"GPU faster ({n_gpu} ops)"),
        plt.Line2D([0], [0], color="k", linestyle="--", label="Equal"),
    ], fontsize=10)
    ax.grid(alpha=0.2, zorder=0)
    fig.tight_layout()
    _save(fig, "fig3_per_op_cpu_vs_gpu.png")


def plot_placement_breakdown(baselines: Dict, methods: List[Dict]) -> None:
    """Stacked bar: demonstrates % of ops per device per strategy."""
    all_devices = ["cpu:0", "gpu:0"]
    dev_colors  = {"cpu:0": "#4C72B0", "gpu:0": "#DD8452"}

    names, pcts = [], {d: [] for d in all_devices}
    for entries in [baselines.items(), ((m["name"], m) for m in methods)]:
        for name, d in entries:
            pl = d.get("placement", {})
            if not pl:
                continue
            total = len(pl)
            names.append(name)
            for dev in all_devices:
                pcts[dev].append(sum(1 for v in pl.values() if v == dev) / total * 100)

    if not names:
        print("  [skip] fig4: no placement data")
        return

    x = np.arange(len(names))
    fig, ax = plt.subplots(figsize=(9, 4.5))
    bottom = np.zeros(len(names))
    for dev in all_devices:
        vals = np.array(pcts[dev])
        if vals.sum() == 0:
            continue
        ax.bar(x, vals, 0.55, bottom=bottom, color=dev_colors[dev], label=dev, alpha=0.88, zorder=3)
        for i, (v, b) in enumerate(zip(vals, bottom)):
            if v > 4:
                ax.text(i, b + v / 2, f"{v:.0f}%", ha="center", va="center",
                        fontsize=9, color="white", fontweight="bold")
        bottom += vals

    ax.set_xticks(x); ax.set_xticklabels(names, rotation=10, ha="right")
    ax.set_ylabel("% of ops assigned to device"); ax.set_ylim(0, 110)
    ax.set_title("Placement Policy: Op Distribution Across Devices per Strategy")
    ax.legend(title="Device", fontsize=10); ax.grid(axis="y", alpha=0.3, zorder=0)
    fig.tight_layout()
    _save(fig, "fig4_placement_breakdown.png")


def print_summary(baselines: Dict, methods: List[Dict]) -> None:
    cpu_rt = baselines.get("CPU-only", {}).get("runtime")
    print("\n" + "=" * 65)
    print(f"{'Strategy':<22} {'Latency (ms)':>14} {'vs CPU-only':>12} {'Comm (MB)':>11}")
    print("-" * 65)
    for name, d in baselines.items():
        spd = f"{cpu_rt/d['runtime']:.2f}×" if cpu_rt else "—"
        print(f"{name:<22} {d['runtime']*1000:>14.3f} {spd:>12} {d['comm_bytes']/1e6:>11.3f}")
    for m in methods:
        spd = f"{cpu_rt/m['runtime']:.2f}×" if cpu_rt else "—"
        print(f"{m['name']:<22} {m['runtime']*1000:>14.3f} {spd:>12} {m.get('comm_bytes', 0)/1e6:>11.3f}")
    print("=" * 65)


# ── Main ─────────────────────────────────────────────────────────────────

def main() -> None:
    print("Reinformer — Device Placement Analysis")

    ops: List[Dict] = json.loads(GRAPH_PATH.read_text(encoding="utf-8"))["ops"]
    print(f"Graph: {len(ops)} ops  ({GRAPH_PATH.name})\n")

    # Baselines from baseline_results.json (run run_baselines.py to generate)
    if not BASELINE_RESULTS.exists():
        print(f"[error] {BASELINE_RESULTS.name} not found.")
        print(f"        Run first:  python run_baselines.py")
        return

    baselines: Dict[str, Dict] = {}
    for name, d in json.loads(BASELINE_RESULTS.read_text(encoding="utf-8")).items():
        entry = _parse_entry(name, d, ops)
        if entry:
            baselines[name] = entry
            print(f"  {name}: {entry['runtime']*1000:.3f} ms")

    # RL / SCOTCH methods from rl_results_template.json
    methods: List[Dict] = []
    if RL_RESULTS_PATH.exists():
        print(f"\nLoading from {RL_RESULTS_PATH.name}...")
        for m in json.loads(RL_RESULTS_PATH.read_text(encoding="utf-8")).get("methods", []):
            if not m.get("name") or m["name"].startswith("_"):
                continue
            entry = _parse_entry(m["name"], m, ops)
            if entry:
                methods.append(entry)
                print(f"  {m['name']}: {entry['runtime']*1000:.3f} ms  "
                      f"({entry['comm_bytes']/1e6:.1f} MB xfer)")
    else:
        print(f"\n[info] No rl_results.json — add SCOTCH and RL entries there")

    print(f"\nGenerating figures → {OUT_DIR}")
    plot_runtime_comparison(baselines, methods)
    plot_training_curve(baselines, methods)
    plot_per_op_scatter(ops)
    plot_placement_breakdown(baselines, methods)
    print_summary(baselines, methods)


if __name__ == "__main__":
    main()